ALTER TABLE CRYPTOCOIN
    ALTER COLUMN ID SET NOT NULL;

ALTER TABLE CRYPTOCOIN
    ADD CONSTRAINT id_constraint UNIQUE (ID);

ALTER TABLE CRYPTOCOIN
    RENAME COLUMN NAME TO SYMBOL;

ALTER TABLE CRYPTOCOIN
    ALTER COLUMN SYMBOL SET NOT NULL;

ALTER TABLE CRYPTOCOIN
    ADD usd_price DECIMAL;

-- UPDATE CRYPTOCOIN SET usdPrice = '' where usdPrice IS NULL;

ALTER TABLE CRYPTOCOIN
    ALTER COLUMN usd_price SET NOT NULL;

ALTER TABLE CRYPTOCOIN
    ADD CONSTRAINT symbol_constraint UNIQUE (SYMBOL);

